### ISSUE TITLE
Code for sine curve generation

### ISSUE THREAD

**Issue by markusdumke** [Brophy-E/ECG_GAN_MBD#1]
Hi, 

thank you for your very interesting paper about GANs to generate artificial time series. This is a very exciting field of research 👍 

I have a similar use case where I want to generate artificial time series and try to reproduce your results to get a feeling for GANs. I want to start with the simple sine curve example to get a feeling for the model and then adjust this for my (complex) data 😊

Can you share the code with which you generate the sine curves (especially Figures 3 & 4)? I could not find this in the repository. 

Thanks

**Comment by Brophy-E** [comment]
Hi @markusdumke,

Thanks for your kind words, we are particularly interested in furthering this work just like you. 😀

As this was not a peer reviewed paper and I am not the corresponding author, we were not the most stringent with our code documentation. But not to fear, we are working on updating this and should have the code live shortly. 

I will also leave a link to the corresponding author's GitHub account once sorted, thanks for your patience. 👍 And keep an eye out for our future work!

**Comment by Brophy-E** [comment]
The folder [Sine Generation](https://github.com/Brophy-E/ECG_GAN_MBD/tree/master/Sine%20Generation) has been uploaded which was used for generating the sine wave signals seen in the paper. 

We will be creating a cleaner and more comprehensive repo shortly, thanks for your patience!
